using Border.Application.Operations;
using Border.Domain.Entities;
using Border.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace Border.Infrastructure.Operations;

internal sealed class ReportingService(BorderDbContext db) : IReportingService
{
    private static DateTime IstanbulStart(DateOnly date) => DateTime.SpecifyKind(date.ToDateTime(TimeOnly.MinValue).AddHours(-3), DateTimeKind.Utc);
    private static DateOnly IstanbulDate(DateTime value) => DateOnly.FromDateTime(value.AddHours(3));
    private static decimal? Trend(decimal current, decimal previous) => previous == 0 ? null : Math.Round(100m * (current - previous) / previous, 1);
    private static (DateOnly From, DateOnly To) Previous(ReportFilter filter) { var days = filter.To.DayNumber - filter.From.DayNumber + 1; return (filter.From.AddDays(-days), filter.From.AddDays(-1)); }

    public async Task<ReportingSummaryResponse> GetSummaryAsync(ReportFilter filter, CancellationToken ct)
    {
        var previous = Previous(filter); var endUtc = IstanbulStart(filter.To.AddDays(1)); var previousEndUtc = IstanbulStart(previous.To.AddDays(1));
        var students = StudentScope(db.Students.AsNoTracking().Where(x => !x.IsDeleted), filter);
        var active = await students.CountAsync(x => x.Status == StudentStatus.Active, ct);
        var newStudents = await students.CountAsync(x => x.RegistrationDate >= filter.From && x.RegistrationDate <= filter.To, ct);
        var previousNew = await students.CountAsync(x => x.RegistrationDate >= previous.From && x.RegistrationDate <= previous.To, ct);
        var memberships = MembershipScope(db.StudentMemberships.AsNoTracking().Where(x => !x.Student.IsDeleted), filter);
        var activeMemberships = await memberships.CountAsync(x => x.Status == MembershipStatus.Active && x.StartDate <= filter.To && (x.EndDate == null || x.EndDate >= filter.To), ct);
        var previousMemberships = await memberships.CountAsync(x => x.Status == MembershipStatus.Active && x.StartDate <= previous.To && (x.EndDate == null || x.EndDate >= previous.To), ct);
        var payments = PaymentScope(db.Payments.AsNoTracking().Where(x => !x.Student.IsDeleted), filter);
        var revenue = await payments.Where(x => x.PaymentDate >= IstanbulStart(filter.From) && x.PaymentDate < endUtc).SumAsync(x => (decimal?)x.Amount, ct) ?? 0;
        var previousRevenue = await payments.Where(x => x.PaymentDate >= IstanbulStart(previous.From) && x.PaymentDate < previousEndUtc).SumAsync(x => (decimal?)x.Amount, ct) ?? 0;
        var balance = await BalanceAtAsync(filter, filter.From, filter.To, ct); var previousBalance = await BalanceAtAsync(filter, previous.From, previous.To, ct);
        var attendance = await AttendanceRateAsync(filter, filter.From, filter.To, ct); var previousAttendance = await AttendanceRateAsync(filter, previous.From, previous.To, ct);
        return new(new(active, null), new(newStudents, Trend(newStudents, previousNew)), new(activeMemberships, Trend(activeMemberships, previousMemberships)), new(revenue, Trend(revenue, previousRevenue)), new(balance.Outstanding, Trend(balance.Outstanding, previousBalance.Outstanding)), new(attendance, Trend(attendance, previousAttendance)));
    }

    public async Task<ReportingFinanceResponse> GetFinanceAsync(ReportFilter filter, CancellationToken ct)
    {
        var startUtc = IstanbulStart(filter.From); var endUtc = IstanbulStart(filter.To.AddDays(1));
        var payments = await PaymentScope(db.Payments.AsNoTracking().Where(x => !x.Student.IsDeleted && x.PaymentDate >= startUtc && x.PaymentDate < endUtc), filter)
            .Select(x => new { x.PaymentDate, x.Amount, x.PaymentMethod }).ToListAsync(ct);
        var trend = Series(payments.Select(x => (IstanbulDate(x.PaymentDate), x.Amount)), filter);
        var peak = trend.OrderByDescending(x => x.Value).FirstOrDefault();
        var methods = payments.GroupBy(x => x.PaymentMethod).Select(x => new PaymentMethodReport(x.Key, x.Count(), x.Sum(p => p.Amount))).OrderByDescending(x => x.Amount).ToList();
        var revenue = new RevenueReport(payments.Sum(x => x.Amount), payments.Count, payments.Count == 0 ? 0 : Math.Round(payments.Average(x => x.Amount), 2), methods, trend, peak?.Label, peak?.Value);
        var invoiceRows = await InvoiceRowsAsync(filter, filter.From, filter.To, ct); var asOf = filter.To < Today() ? filter.To : Today();
        var statuses = invoiceRows.GroupBy(x => CalculatedStatus(x.Status, x.Amount, x.Paid)).Select(x => new InvoiceStatusReport(x.Key, x.Count(), x.Sum(i => i.Amount))).OrderBy(x => x.Status).ToList();
        var debtors = invoiceRows.Where(x => x.Status != InvoiceStatus.Cancelled).GroupBy(x => new { x.StudentId, x.StudentName }).Select(x => new StudentBalanceReport(x.Key.StudentId, x.Key.StudentName, x.Sum(i => i.Amount), x.Sum(i => i.Paid), x.Sum(i => Math.Max(0, i.Amount - i.Paid)))).Where(x => x.Outstanding > 0).OrderByDescending(x => x.Outstanding).Take(10).ToList();
        var balances = new BalanceReport(invoiceRows.Where(x => x.Status != InvoiceStatus.Cancelled).Sum(x => x.Amount), invoiceRows.Where(x => x.Status != InvoiceStatus.Cancelled).Sum(x => x.Paid), invoiceRows.Where(x => x.Status != InvoiceStatus.Cancelled).Sum(x => Math.Max(0, x.Amount - x.Paid)), invoiceRows.Where(x => x.Status != InvoiceStatus.Cancelled && x.DueDate < asOf).Sum(x => Math.Max(0, x.Amount - x.Paid)), invoiceRows.Count(x => x.Status != InvoiceStatus.Cancelled && x.DueDate < asOf && x.Amount > x.Paid), statuses, debtors);
        return new(revenue, balances);
    }

    public async Task<ReportingEngagementResponse> GetEngagementAsync(ReportFilter filter, CancellationToken ct)
    {
        var students = await StudentScope(db.Students.AsNoTracking().Where(x => !x.IsDeleted && x.RegistrationDate <= filter.To), filter).Select(x => new { x.Status, x.RegistrationDate }).ToListAsync(ct);
        var studentReport = new StudentReport(students.Count, students.Count(x => x.Status == StudentStatus.Active), students.Count(x => x.Status == StudentStatus.Trial), students.Count(x => x.Status == StudentStatus.Frozen), students.Count(x => x.Status == StudentStatus.Passive), students.Count(x => x.Status == StudentStatus.Left), students.Count(x => x.RegistrationDate >= filter.From), Enum.GetValues<StudentStatus>().Select(status => new ReportSeriesPoint(status.ToString(), students.Count(x => x.Status == status))).ToList(), Series(students.Where(x => x.RegistrationDate >= filter.From).Select(x => (x.RegistrationDate, 1m)), filter));
        var startUtc = IstanbulStart(filter.From); var endUtc = IstanbulStart(filter.To.AddDays(1));
        var attendanceRows = await AttendanceScope(db.Attendances.AsNoTracking().Where(x => x.LessonSession.ScheduledStart >= startUtc && x.LessonSession.ScheduledStart < endUtc), filter)
            .Select(x => new { x.Status, x.LessonSession.ScheduledStart, x.LessonSession.StudioClassId, x.LessonSession.StudioClass.Name }).ToListAsync(ct);
        var attendanceTrend = attendanceRows.GroupBy(x => IstanbulDate(x.ScheduledStart)).Select(x => (x.Key, Rate(x.Count(a => AttendanceReportingRules.CountsAsAttended(a.Status)), x.Count())));
        var classes = attendanceRows.GroupBy(x => new { x.StudioClassId, x.Name }).Select(x => new AttendanceClassReport(x.Key.StudioClassId, x.Key.Name, x.Count(), Rate(x.Count(a => AttendanceReportingRules.CountsAsAttended(a.Status)), x.Count()))).OrderByDescending(x => x.Rate).ToList();
        var sessions = SessionScope(db.LessonSessions.AsNoTracking().Where(x => !x.StudioClass.IsDeleted && x.ScheduledStart >= startUtc && x.ScheduledStart < endUtc && x.Status != LessonSessionStatus.Cancelled), filter);
        var missing = await sessions.CountAsync(x => x.ScheduledEnd < DateTime.UtcNow && x.Status == LessonSessionStatus.Scheduled && !db.Attendances.Any(a => a.LessonSessionId == x.Id), ct);
        var attendanceReport = new AttendanceReport(attendanceRows.Count, attendanceRows.Count(x => x.Status == AttendanceStatus.Present), attendanceRows.Count(x => x.Status == AttendanceStatus.Absent), attendanceRows.Count(x => x.Status == AttendanceStatus.Excused), attendanceRows.Count(x => x.Status == AttendanceStatus.Late), attendanceRows.Count(x => x.Status == AttendanceStatus.MakeUp), AttendanceReportingRules.Rate(attendanceRows.Count(x => x.Status == AttendanceStatus.Present), attendanceRows.Count(x => x.Status == AttendanceStatus.Late), attendanceRows.Count), missing, Series(attendanceTrend, filter), classes);
        return new(studentReport, attendanceReport);
    }

    public async Task<ReportingCapacityResponse> GetCapacityAsync(ReportFilter filter, CancellationToken ct)
    {
        var classes = await ClassScope(db.StudioClasses.AsNoTracking().Where(x => !x.IsDeleted && x.Status == StudioClassStatus.Active), filter)
            .OrderBy(x => x.Name).Select(x => new ClassOccupancyReport(x.Id, x.Name, x.InstructorId, x.Instructor.FirstName + " " + x.Instructor.LastName, x.StudioRoom.Name, x.Capacity, db.ClassEnrollments.Count(e => e.StudioClassId == x.Id && e.Status == EnrollmentStatus.Active && !e.Student.IsDeleted && e.StartDate <= filter.To && (e.EndDate == null || e.EndDate >= filter.To)), Math.Round(100m * db.ClassEnrollments.Count(e => e.StudioClassId == x.Id && e.Status == EnrollmentStatus.Active && !e.Student.IsDeleted && e.StartDate <= filter.To && (e.EndDate == null || e.EndDate >= filter.To)) / x.Capacity, 1))).ToListAsync(ct);
        var startUtc = IstanbulStart(filter.From); var endUtc = IstanbulStart(filter.To.AddDays(1));
        var sessions = await SessionScope(db.LessonSessions.AsNoTracking().Where(x => x.ScheduledStart >= startUtc && x.ScheduledStart < endUtc && x.Status != LessonSessionStatus.Cancelled), filter).Select(x => new { x.InstructorId }).ToListAsync(ct);
        var attendance = await AttendanceScope(db.Attendances.AsNoTracking().Where(x => x.LessonSession.ScheduledStart >= startUtc && x.LessonSession.ScheduledStart < endUtc), filter).Select(x => new { x.Status, x.LessonSession.InstructorId }).ToListAsync(ct);
        var instructorStudentsQuery = db.ClassEnrollments.AsNoTracking().Where(x => x.Status == EnrollmentStatus.Active && !x.Student.IsDeleted && !x.StudioClass.IsDeleted && x.StartDate <= filter.To && (x.EndDate == null || x.EndDate >= filter.To));
        if (filter.InstructorId.HasValue) instructorStudentsQuery = instructorStudentsQuery.Where(x => x.StudioClass.InstructorId == filter.InstructorId);
        if (filter.ClassId.HasValue) instructorStudentsQuery = instructorStudentsQuery.Where(x => x.StudioClassId == filter.ClassId);
        if (filter.RoomId.HasValue) instructorStudentsQuery = instructorStudentsQuery.Where(x => x.StudioClass.StudioRoomId == filter.RoomId);
        var instructorStudents = await instructorStudentsQuery.Select(x => new { x.StudioClass.InstructorId, x.StudentId }).Distinct().ToListAsync(ct);
        var instructorsQuery = db.Instructors.AsNoTracking().Where(x => !x.IsDeleted); if (filter.InstructorId.HasValue) instructorsQuery = instructorsQuery.Where(x => x.Id == filter.InstructorId); var instructors = await instructorsQuery.Select(x => new { x.Id, Name = x.FirstName + " " + x.LastName }).ToListAsync(ct);
        var instructorReports = instructors.Select(x => { var ownedClasses = classes.Where(c => c.InstructorId == x.Id).ToList(); var rows = attendance.Where(a => a.InstructorId == x.Id).ToList(); return new InstructorReport(x.Id, x.Name, ownedClasses.Count, instructorStudents.Where(s => s.InstructorId == x.Id).Select(s => s.StudentId).Distinct().Count(), sessions.Count(s => s.InstructorId == x.Id), ownedClasses.Count == 0 ? 0 : Math.Round(ownedClasses.Average(c => c.OccupancyRate), 1), Rate(rows.Count(a => AttendanceReportingRules.CountsAsAttended(a.Status)), rows.Count)); }).Where(x => x.ActiveClasses > 0 || x.Sessions > 0).OrderByDescending(x => x.Sessions).ToList();
        var membershipRows = await MembershipScope(db.StudentMemberships.AsNoTracking().Where(x => !x.Student.IsDeleted && x.StartDate <= filter.To), filter).Select(x => new { x.Id, x.StudentId, StudentName = x.Student.FirstName + " " + x.Student.LastName, x.MembershipPlanId, PlanName = x.MembershipPlan.Name, x.Status, x.EndDate }).ToListAsync(ct);
        var ids = membershipRows.Select(x => x.Id).ToList(); var prices = await db.MembershipPriceHistory.AsNoTracking().Where(x => ids.Contains(x.StudentMembershipId) && x.EffectiveFrom <= filter.To).OrderByDescending(x => x.EffectiveFrom).Select(x => new { x.StudentMembershipId, x.Price, x.DiscountAmount }).ToListAsync(ct);
        var invoices = await InvoiceScope(db.Invoices.AsNoTracking().Where(x => x.StudentMembershipId != null && x.CreatedAt >= startUtc && x.CreatedAt < endUtc), filter).Select(x => new { MembershipId = x.StudentMembershipId!.Value, x.Amount }).ToListAsync(ct);
        var plans = membershipRows.GroupBy(x => new { x.MembershipPlanId, x.PlanName }).Select(group => { var groupIds = group.Select(x => x.Id).ToHashSet(); var currentPrices = prices.Where(x => groupIds.Contains(x.StudentMembershipId)).GroupBy(x => x.StudentMembershipId).Select(x => x.First()).ToList(); return new MembershipPlanReport(group.Key.MembershipPlanId, group.Key.PlanName, group.Count(x => x.Status == MembershipStatus.Active), invoices.Where(x => groupIds.Contains(x.MembershipId)).Sum(x => x.Amount), currentPrices.Count == 0 ? 0 : Math.Round(currentPrices.Average(x => x.Price - (x.DiscountAmount ?? 0)), 2), currentPrices.Count(x => x.DiscountAmount > 0)); }).OrderByDescending(x => x.ActiveStudents).ToList();
        var asOf = filter.To < Today() ? filter.To : Today(); var expiring = membershipRows.Where(x => x.Status == MembershipStatus.Active && x.EndDate >= asOf && x.EndDate <= asOf.AddDays(30)).Select(x => new ExpiringMembershipReport(x.Id, x.StudentId, x.StudentName, x.PlanName, x.EndDate!.Value, x.EndDate.Value.DayNumber - asOf.DayNumber)).OrderBy(x => x.EndDate).ToList();
        var membershipReport = new MembershipReport(membershipRows.Count(x => x.Status == MembershipStatus.Active), membershipRows.Count(x => x.Status == MembershipStatus.Frozen), membershipRows.Count(x => x.Status == MembershipStatus.Expired), membershipRows.Count(x => x.Status == MembershipStatus.Cancelled), plans, expiring);
        return new(classes, instructorReports, membershipReport);
    }

    private IQueryable<Student> StudentScope(IQueryable<Student> query, ReportFilter filter) { if (filter.InstructorId.HasValue || filter.ClassId.HasValue || filter.RoomId.HasValue) query = query.Where(x => db.ClassEnrollments.Any(e => e.StudentId == x.Id && (!filter.InstructorId.HasValue || e.StudioClass.InstructorId == filter.InstructorId) && (!filter.ClassId.HasValue || e.StudioClassId == filter.ClassId) && (!filter.RoomId.HasValue || e.StudioClass.StudioRoomId == filter.RoomId))); return query; }
    private IQueryable<Payment> PaymentScope(IQueryable<Payment> query, ReportFilter filter) { if (filter.InstructorId.HasValue || filter.ClassId.HasValue || filter.RoomId.HasValue) query = query.Where(x => db.ClassEnrollments.Any(e => e.StudentId == x.StudentId && (!filter.InstructorId.HasValue || e.StudioClass.InstructorId == filter.InstructorId) && (!filter.ClassId.HasValue || e.StudioClassId == filter.ClassId) && (!filter.RoomId.HasValue || e.StudioClass.StudioRoomId == filter.RoomId))); return query; }
    private IQueryable<Invoice> InvoiceScope(IQueryable<Invoice> query, ReportFilter filter) { if (filter.InstructorId.HasValue || filter.ClassId.HasValue || filter.RoomId.HasValue) query = query.Where(x => db.ClassEnrollments.Any(e => e.StudentId == x.StudentId && (!filter.InstructorId.HasValue || e.StudioClass.InstructorId == filter.InstructorId) && (!filter.ClassId.HasValue || e.StudioClassId == filter.ClassId) && (!filter.RoomId.HasValue || e.StudioClass.StudioRoomId == filter.RoomId))); return query; }
    private IQueryable<StudentMembership> MembershipScope(IQueryable<StudentMembership> query, ReportFilter filter) { if (filter.InstructorId.HasValue || filter.ClassId.HasValue || filter.RoomId.HasValue) query = query.Where(x => db.ClassEnrollments.Any(e => e.StudentId == x.StudentId && (!filter.InstructorId.HasValue || e.StudioClass.InstructorId == filter.InstructorId) && (!filter.ClassId.HasValue || e.StudioClassId == filter.ClassId) && (!filter.RoomId.HasValue || e.StudioClass.StudioRoomId == filter.RoomId))); return query; }
    private static IQueryable<LessonSession> SessionScope(IQueryable<LessonSession> query, ReportFilter filter) { if (filter.InstructorId.HasValue) query = query.Where(x => x.InstructorId == filter.InstructorId); if (filter.ClassId.HasValue) query = query.Where(x => x.StudioClassId == filter.ClassId); if (filter.RoomId.HasValue) query = query.Where(x => x.StudioRoomId == filter.RoomId); return query; }
    private static IQueryable<Attendance> AttendanceScope(IQueryable<Attendance> query, ReportFilter filter) { if (filter.InstructorId.HasValue) query = query.Where(x => x.LessonSession.InstructorId == filter.InstructorId); if (filter.ClassId.HasValue) query = query.Where(x => x.LessonSession.StudioClassId == filter.ClassId); if (filter.RoomId.HasValue) query = query.Where(x => x.LessonSession.StudioRoomId == filter.RoomId); return query; }
    private static IQueryable<StudioClass> ClassScope(IQueryable<StudioClass> query, ReportFilter filter) { if (filter.InstructorId.HasValue) query = query.Where(x => x.InstructorId == filter.InstructorId); if (filter.ClassId.HasValue) query = query.Where(x => x.Id == filter.ClassId); if (filter.RoomId.HasValue) query = query.Where(x => x.StudioRoomId == filter.RoomId); return query; }
    private async Task<decimal> AttendanceRateAsync(ReportFilter filter, DateOnly from, DateOnly to, CancellationToken ct) { var q = AttendanceScope(db.Attendances.AsNoTracking().Where(x => x.LessonSession.ScheduledStart >= IstanbulStart(from) && x.LessonSession.ScheduledStart < IstanbulStart(to.AddDays(1))), filter); var row = await q.GroupBy(_ => 1).Select(x => new { Total = x.Count(), Present = x.Count(a => a.Status == AttendanceStatus.Present || a.Status == AttendanceStatus.Late) }).SingleOrDefaultAsync(ct); return row is null ? 0 : Rate(row.Present, row.Total); }
    private async Task<(decimal Outstanding, decimal Paid)> BalanceAtAsync(ReportFilter filter, DateOnly from, DateOnly to, CancellationToken ct) { var rows = await InvoiceRowsAsync(filter, from, to, ct); return (rows.Where(x => x.Status != InvoiceStatus.Cancelled).Sum(x => Math.Max(0, x.Amount - x.Paid)), rows.Where(x => x.Status != InvoiceStatus.Cancelled).Sum(x => x.Paid)); }
    private async Task<List<InvoiceRow>> InvoiceRowsAsync(ReportFilter filter, DateOnly from, DateOnly to, CancellationToken ct) { var start = IstanbulStart(from); var end = IstanbulStart(to.AddDays(1)); return await InvoiceScope(db.Invoices.AsNoTracking().Where(x => !x.Student.IsDeleted && x.CreatedAt >= start && x.CreatedAt < end), filter).Select(x => new InvoiceRow(x.StudentId, x.Student.FirstName + " " + x.Student.LastName, x.Amount, db.Payments.Where(p => p.InvoiceId == x.Id && p.PaymentDate < end).Sum(p => (decimal?)p.Amount) ?? 0, x.DueDate, x.Status)).ToListAsync(ct); }
    private static InvoiceStatus CalculatedStatus(InvoiceStatus status, decimal amount, decimal paid) => status == InvoiceStatus.Cancelled ? status : paid <= 0 ? InvoiceStatus.Pending : paid >= amount ? InvoiceStatus.Paid : InvoiceStatus.PartiallyPaid;
    private static decimal Rate(int present, int total) => AttendanceReportingRules.RateFromAttended(present, total);
    private static List<ReportSeriesPoint> Series(IEnumerable<(DateOnly Date, decimal Value)> rows, ReportFilter filter) { var days = filter.To.DayNumber - filter.From.DayNumber + 1; if (days <= 31) { var sums = rows.GroupBy(x => x.Date).ToDictionary(x => x.Key, x => x.Sum(v => v.Value)); return Enumerable.Range(0, days).Select(offset => filter.From.AddDays(offset)).Select(date => new ReportSeriesPoint(date.ToString("dd.MM"), sums.GetValueOrDefault(date))).ToList(); } if (days <= 120) return rows.GroupBy(x => (x.Date.DayNumber - filter.From.DayNumber) / 7).OrderBy(x => x.Key).Select(x => new ReportSeriesPoint($"{filter.From.AddDays(x.Key * 7):dd.MM}", x.Sum(v => v.Value))).ToList(); return rows.GroupBy(x => new { x.Date.Year, x.Date.Month }).OrderBy(x => x.Key.Year).ThenBy(x => x.Key.Month).Select(x => new ReportSeriesPoint($"{x.Key.Month:00}.{x.Key.Year}", x.Sum(v => v.Value))).ToList(); }
    private static DateOnly Today() => DateOnly.FromDateTime(DateTime.UtcNow.AddHours(3));
    private sealed record InvoiceRow(Guid StudentId, string StudentName, decimal Amount, decimal Paid, DateOnly DueDate, InvoiceStatus Status);
}
