"use client";

import { useQuery } from "@tanstack/react-query";
import { Building2, ChevronLeft, ChevronRight, Plus, Search, UserCog } from "lucide-react";
import Link from "next/link";
import { useDeferredValue, useMemo, useState } from "react";
import { ClassFormDialog } from "@/components/classes/class-form-dialog";
import { ClassStatusBadge } from "@/components/classes/class-status-badge";
import { RoomManagementDialog } from "@/components/classes/room-management-dialog";
import { InstructorManagementDialog } from "@/components/classes/instructor-management-dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useCurrentUser } from "@/hooks/use-current-user";
import { classesApi, classKeys, classStatuses, classStatusLabels, scheduleText } from "@/lib/classes";
import { classDetailHref } from "@/lib/routes";

export default function ClassesPage() {
  const { data: user } = useCurrentUser(); const [search, setSearch] = useState(""); const deferred = useDeferredValue(search); const [status, setStatus] = useState(""); const [instructorId, setInstructorId] = useState(""); const [roomId, setRoomId] = useState(""); const [page, setPage] = useState(1); const [includeArchived, setIncludeArchived] = useState(false); const [createOpen, setCreateOpen] = useState(false); const [roomsOpen, setRoomsOpen] = useState(false); const [instructorsOpen, setInstructorsOpen] = useState(false);
  const canArchive = user?.roles.some((x) => x === "Admin" || x === "Management") ?? false;
  const params = useMemo(() => { const p = new URLSearchParams({ page: String(page), pageSize: "20" }); if (deferred.trim()) p.set("search", deferred.trim()); if (status) p.set("status", status); if (instructorId) p.set("instructorId", instructorId); if (roomId) p.set("roomId", roomId); if (includeArchived && canArchive) p.set("includeArchived", "true"); return p; }, [canArchive, deferred, includeArchived, instructorId, page, roomId, status]);
  const query = useQuery({ queryKey: classKeys.list(params.toString()), queryFn: () => classesApi.list(params), placeholderData: (old) => old });
  const instructors = useQuery({ queryKey: classKeys.instructors, queryFn: classesApi.instructors });
  const rooms = useQuery({ queryKey: classKeys.rooms, queryFn: classesApi.rooms });
  return <div className="mx-auto max-w-7xl"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-[#61734f]">Program ve kapasite yönetimi</p><h1 className="mt-1 text-2xl font-semibold sm:text-3xl">Sınıflar</h1><p className="mt-2 text-sm text-zinc-500">Haftalık programları, eğitmenleri ve öğrenci kontenjanlarını yönetin.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setInstructorsOpen(true)}><UserCog />Eğitmenler</Button><Button variant="outline" onClick={() => setRoomsOpen(true)}><Building2 />Stüdyolar</Button><Button className="bg-[#20241f]" onClick={() => setCreateOpen(true)}><Plus />Yeni sınıf</Button></div></header>
    <section className="mt-7 overflow-hidden rounded-xl border bg-white shadow-sm"><div className="grid gap-3 border-b p-4 sm:grid-cols-2 xl:grid-cols-[minmax(240px,1fr)_180px_200px_180px_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-zinc-400" size={17} /><Input className="pl-9" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Sınıf, eğitmen veya stüdyo ara" /></div><select aria-label="Duruma göre filtrele" className="h-9 rounded-lg border bg-white px-3 text-sm" value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="">Tüm durumlar</option>{classStatuses.map((x) => <option key={x} value={x}>{classStatusLabels[x]}</option>)}</select><select aria-label="Eğitmene göre filtrele" className="h-9 rounded-lg border bg-white px-3 text-sm" value={instructorId} onChange={(e) => { setInstructorId(e.target.value); setPage(1); }}><option value="">Tüm eğitmenler</option>{instructors.data?.map((x) => <option key={x.id} value={x.id}>{x.fullName}</option>)}</select><select aria-label="Stüdyoya göre filtrele" className="h-9 rounded-lg border bg-white px-3 text-sm" value={roomId} onChange={(e) => { setRoomId(e.target.value); setPage(1); }}><option value="">Tüm stüdyolar</option>{rooms.data?.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select>{canArchive && <label className="flex h-9 items-center gap-2 rounded-lg border px-3 text-sm"><input type="checkbox" checked={includeArchived} onChange={(e) => setIncludeArchived(e.target.checked)} />Arşiv</label>}</div>
      {query.isLoading ? <div className="space-y-3 p-5">{Array.from({ length: 5 }).map((_, i) => <div key={i} className="h-14 animate-pulse rounded bg-zinc-100" />)}</div> : query.isError ? <State text="Sınıflar yüklenemedi." /> : !query.data?.items.length ? <State text="Filtrelerle eşleşen sınıf bulunamadı." /> : <><div className="hidden md:block"><Table><TableHeader><TableRow><TableHead className="pl-5">Sınıf</TableHead><TableHead>Program</TableHead><TableHead>Stüdyo</TableHead><TableHead>Doluluk</TableHead><TableHead>Durum</TableHead></TableRow></TableHeader><TableBody>{query.data.items.map((item) => <TableRow key={item.id}><TableCell className="pl-5"><Link href={classDetailHref(item.id)} className="font-medium hover:text-[#526743]">{item.name}</Link><p className="text-xs text-zinc-500">{item.instructorName}{item.isArchived ? " · Arşivlendi" : ""}</p></TableCell><TableCell className="max-w-xs text-sm text-zinc-600">{scheduleText(item.schedules)}</TableCell><TableCell>{item.roomName}</TableCell><TableCell><span className={item.activeStudentCount >= item.capacity ? "font-medium text-red-700" : ""}>{item.activeStudentCount}/{item.capacity}</span></TableCell><TableCell><ClassStatusBadge status={item.status} /></TableCell></TableRow>)}</TableBody></Table></div><div className="divide-y md:hidden">{query.data.items.map((item) => <Link href={classDetailHref(item.id)} key={item.id} className="block p-4 active:bg-zinc-50"><div className="flex justify-between gap-3"><div><p className="font-medium">{item.name}</p><p className="mt-1 text-sm text-zinc-500">{item.instructorName} · {item.roomName}</p></div><ClassStatusBadge status={item.status} /></div><p className="mt-3 text-sm text-zinc-600">{scheduleText(item.schedules)}</p><p className="mt-2 text-xs text-zinc-400">Doluluk {item.activeStudentCount}/{item.capacity}</p></Link>)}</div></>}
      {query.data && query.data.totalCount > 0 && <div className="flex items-center justify-between border-t p-4"><p className="text-sm text-zinc-500">{query.data.totalCount} sınıf · {query.data.page}/{Math.max(1, query.data.totalPages)}</p><div className="flex gap-2"><Button size="icon-sm" variant="outline" disabled={page <= 1} onClick={() => setPage((x) => x - 1)}><ChevronLeft /></Button><Button size="icon-sm" variant="outline" disabled={page >= query.data.totalPages} onClick={() => setPage((x) => x + 1)}><ChevronRight /></Button></div></div>}
    </section><ClassFormDialog open={createOpen} onOpenChange={setCreateOpen} /><RoomManagementDialog open={roomsOpen} onOpenChange={setRoomsOpen} /><InstructorManagementDialog open={instructorsOpen} onOpenChange={setInstructorsOpen} /></div>;
}
function State({ text }: { text: string }) { return <div className="grid min-h-64 place-items-center p-8 text-sm text-zinc-500">{text}</div>; }
